
model_name: "MobileNetV2"     # Какую pre-trained модель использовать как основу
input_shape: [224, 224, 3]    # Входной размер изображений для классификатора [высота, ширина, каналы]
num_classes: 2                # Количество классов для классификатора: 'road', 'not_road'
freeze_base_model: true       # Заморозить ли веса базовой pre-trained модели на начальном этапе обучения

train_params:
  batch_size: 1             # Количество изображений, обрабатываемых за один шаг обучения
  epochs: 3                 # Начальное количество эпох для обучения классификатора
  learning_rate: 0.001        # Скорость обучения

# Путь к подготовленному датасету для классификатора (относительно корня проекта)
# Сюда скрипт prepare_classifier_dataset.py будет копировать данные
prepared_dataset_path: "data/Classifier_Dataset"
train_ratio: 1              # Доля данных, которая пойдет в обучающую выборку (остальное - в валидационную)