model_name: "CustomObjectDetector"
backbone_name: "MobileNetV2"
input_shape: [416, 416, 3]
freeze_backbone: true
classes: ["pit", "crack"]
num_classes: 2
head_conv_filters: 128
max_boxes_per_image: 10 # Это значение используется в losses и models

train_params:
  batch_size: 1
  epochs: 50 # Это было для classifier, для detector epochs_test_overfit
  learning_rate: 0.0001
  epochs_test_overfit: 100 # Для train_detector.py