model_name: "CustomObjectDetector"
backbone_name: "MobileNetV2"
input_shape: [416, 416, 3]
freeze_backbone: true
classes: ["pit", "crack"]
num_classes: 2
head_conv_filters: 128
max_boxes_per_image: 10 # Это значение используется в losses и models

train_params:
  batch_size: 1
  epochs: 50 # Это было для classifier, для detector epochs_test_overfit
  learning_rate: 0.0001
  epochs_test_overfit: 100 # Для train_detector.py


anchors_wh_normalized: # [width, height] нормализованные
  - [0.05, 0.05]  # Маленький квадратный
  - [0.1,  0.05]  # Маленький горизонтальный
  - [0.05, 0.1]   # Маленький вертикальный


loss_weights:
    coordinates: 1.0  # Вес для потерь координат
    objectness: 1.0   # Вес для потерь objectness (когда объект есть)
    no_object: 0.5    # Вес для потерь objectness (когда объекта нет - фон)
    classification: 1.0 # Вес для потерь классификации