# src/configs/detector_config.yaml

# --- Общие Параметры Модели Детектора ---
model_base_name: "RoadDefectDetector_v2_FPN"
backbone_name: "MobileNetV2"
input_shape: [416, 416, 3]
backbone_layer_name_in_model: "Backbone_MobileNetV2_FPN"

# Параметры FPN "Шеи" и "Голов" предсказаний
fpn_filters: 256
head_depth: 2
head_conv_filters: 256
leaky_relu_alpha: 0.1
l2_regularization: null # Начнем без L2 регуляризации, добавим если будет переобучение

# --- Параметры Классов ---
classes: ["pit", "crack"]
num_classes: 2

# --- Параметры Якорей для FPN (ОБНОВЛЕНО НА ОСНОВЕ K-MEANS) ---
fpn_anchor_configs:
  P3: # stride 8 (для мелких объектов)
    anchors_wh_normalized: # [width, height]
      - [0.0619, 0.0351]
      - [0.1185, 0.0488]
      - [0.0848, 0.0807]
      - [0.0450, 0.1696]
      - [0.1728, 0.0444]
    num_anchors_this_level: 5 # <<<--- ИЗМЕНЕНО
    stride: 8
  P4: # stride 16 (для средних объектов)
    anchors_wh_normalized:
      - [0.1778, 0.1362]
      - [0.0866, 0.3607]
      - [0.3371, 0.1366]
      - [0.5888, 0.0938]
      - [0.0774, 0.7760]
    num_anchors_this_level: 5 # <<<--- ИЗМЕНЕНО
    stride: 16
  P5: # stride 32 (для крупных объектов)
    anchors_wh_normalized:
      - [0.4437, 0.3374]
      - [0.8474, 0.2648]
      - [0.2750, 0.8508]
      - [0.7387, 0.6085]
    num_anchors_this_level: 4 # <<<--- ИЗМЕНЕНО
    stride: 32

# --- Режим и Параметры Обучения ---
# НАЧАЛЬНОЕ ОБУЧЕНИЕ НОВОЙ FPN МОДЕЛИ С ЗАМОРОЖЕННЫМ BACKBONE НА ПОЛНОМ ДАТАСЕТЕ
continue_from_checkpoint: false
path_to_checkpoint: ""

unfreeze_backbone: false
finetune_keep_bn_frozen: true # Важно для будущего fine-tuning'а
unfreeze_backbone_layers_from_end: 0 # Не влияет, пока unfreeze_backbone: false

batch_size: 4
epochs: 150   # С EarlyStopping

# Learning Rates
initial_learning_rate: 0.001 # Можно начать с этого для Adam
finetune_learning_rate: 0.00001

# Параметры Callbacks
early_stopping_patience: 25
reduce_lr_patience: 10
reduce_lr_factor: 0.2
min_lr_on_plateau: 0.0000001 # 1e-7

# Аугментация
use_augmentation: true

# --- Параметры Функции Потерь ---
loss_weights:
  coordinates: 1.0    # Начнем с более сбалансированных весов
  objectness: 1.0
  no_object: 0.5
  classification: 1.0

# --- Параметры для Инференса ---
predict_params:
  confidence_threshold: 0.25
  iou_threshold: 0.45
  max_detections: 100

# (Опционально) Путь к папке с разделенным датасетом для детектора
# Это используется в calculate_anchors.py и train_detector.py для нахождения данных
prepared_detector_dataset_path: "data/Detector_Dataset_Ready"

