
classifier_model_path: "weights/classifier_trained_model_best.keras"
detector_model_path: "weights/RoadDefectDetector_v1_finetune_bb_best.keras"
output_path_template: "results/{image_name}_predicted.{ext}"
default_conf_thresh: 0.1
default_iou_thresh: 0.5
default_max_dets: 100
