
classifier_model_path: "weights/classifier_trained_model_best.keras"
detector_model_path: "weights/detector_v1_best_val_loss.keras"
output_path_template: "results/{image_name}_predicted.{ext}"
default_conf_thresh: 0.01
default_iou_thresh: 0.01
default_max_dets: 100
